"""empty message

Revision ID: 4e0234a8f61f
Revises: b99221ee41c5
Create Date: 2023-12-11 14:41:07.745842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0234a8f61f'
down_revision = 'b99221ee41c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('givers_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('gifts_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('giver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_gifts_table_giver_id_givers_table'), 'givers_table', ['giver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gifts_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_gifts_table_giver_id_givers_table'), type_='foreignkey')
        batch_op.drop_column('giver_id')

    op.drop_table('givers_table')
    # ### end Alembic commands ###
